---
 - name: VARS
   include_vars: ../../../vars.yml

 # configuring mysql
 - name: configure mysql
   copy: src=mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf
   notify:
         restart mysql service

 - name: create database
   mysql_db: name={{wordpress_db}} state=present

 - name: create user
   mysql_user: name={{wordpress_db_user}} password={{wordpress_db_password}} priv={{wordpress_db_user}}.*:ALL host='%' state=present
   notify:
         restart mysql service

